version: '3'
services:
  download:
    image: dbpedia/minimal-download-client:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/jan/collections/large-cities/
      TARGET_DIR: /root/data
    volumes:
      - ./downloads:/root/data
  store:
    image: openlink/virtuoso-opensource-7
    ports: ["${VIRTUOSO_HTTP_PORT}:8890","127.0.0.1:${VIRTUOSO_ISQL_PORT}:1111"]
    environment:
            DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
    volumes:
      - ./virtuoso-db:/opt/virtuoso-opensource/database
      - ./downloads:/usr/share/proj
  load:
    image: dbpedia/dbpedia-virtuoso-loader:latest
    environment:
      STORE_DATA_DIR: /usr/share/proj
      STORE_DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
      STORE_ISQL_PORT: 1111
      DATA_DIR: /root/data
      DOMAIN: http://dbpedia.org 
    volumes:
      - ./downloads:/root/data 
